server:
  port: 8763  # 端口号
spring:
  application:
    name: springcloud-zuul-server # 服务名称

# 注册中心配置


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  # 注册中心的地址 集群的多台机器用,隔开

  instance:
    prefer-ip-address: true # 是否以ip的形式显示 默认是以主机的形式显示

# 服务路由配置
zuul:
#  prefix: web # 表示url的开头必须要有web
#  strip-prefix: false
  routes:
    springcloud-eureka-client: /client/**
#      stripPrefix: false #是否忽略前缀


#表示API网关在进行请求路由装发前为请求设置host头信息 通常解决重定向后的host错误
  add-host-header: true
  #默认情况下 敏感的头信息无法经过API网关进行传递
  #我们可以通过如下配置使之可以传递 可以解决登录会话无法保持的问题
  sensitive-headers:
#  sensitive-headers:


#断路器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 20000 # 断路器hystrix熔断超时时长: 10000 ms

#负载均衡器ribbon配置
ribbon:
#  eureka:
#    enabled: true
  ConnectTimeout: 2000 #连接超时时间(ms)
  ReadTimeout: 500 # 通信超时时间(ms)
  MaxAutoRetriesNextServer: 0 #同一服务不同实例的重试次数
  MaxAutoRetries: 0 #同一实例的重试次数