# 设置的eureka端口号
server:
  port: 8761
  # 设置eureka的主机地址
eureka:
#  server:
#    enableSelfPreservation: false
  instance:
    instance-id: microservicecloud-dept8001 # 自定义服务名称信息
    hostname: localhost
    prefer-ip-address: true
  #表示是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设置为false
  client:
    registerWithEureka: false
  #表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false
    fetchRegistry: false
  #Eureka server地址，查询服务和注册服务都需要依赖这个地址，多个地址可用逗号（英文的）分割
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  # 服务模块名称
spring:
  application:
    name: springcloud-eureka-server